# SPARK network diagram https://www.ibm.com/docs/en/zpfas/1.1.0?topic=spark-configuring-networking-apache

version: '3.9'
services:
  masternode:
    image: spark-base:v1
    build: .
    hostname: masternode
    ports:
      - "7077:7077" # Spark master
      - "8080:8080" # Master web GUI
      - "9000:9000" # Hadoop NameNode
      - "9870:9870" # HDFS datanode web GUI
    command: hdfs namenode -format && hdfs --daemon start namenode && hdfs --daemon start datanode && sleep 999999d
    networks:
      - spark-network

networks:
  spark-network: {}